# This workflow will install Python dependencies using Conda, run tests and lint with a single version of Python
# For more information see: https://autobencoder.com/2020-08-24-conda-actions/

name: Mamba PyTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, grid-detector ]
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1" #run every Monday night at 1AM UTC

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        python-version: ["3.12"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - name: provision-with-micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        environment-name: smmregrid
        cache-downloads: true
        cache-environment: false
        condarc: |
          channels:
            - conda-forge
        create-args: >-
              python=${{ matrix.python-version }}
    - name: Install smmregrid
      run: |
        # install package
        python -m pip install --editable .
    - name: Lint with flake8
      run: |
        # install flake8
        python -m pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install coverage tools
      run: |
        python -m pip install coverage
        python -m pip install coveralls
    - name: Run coverage
      run: |
        coverage run -m pytest
        coverage lcov
    - name: Run coveralls
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov

